config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,  only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only:[:new,:create,:show,:index]
  post 'events/join', to: 'events#join', as: 'event_join'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/created_event.rb
class CreatedEvent < ApplicationRecord
  belongs_to :creator, :class_name => 'User'
  belongs_to :event, :class_name =>'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :created_events, :foreign_key => "event_id"
  has_many :creators, :through => :created_events, :source => :creator

  has_many :event_attendee, :foreign_key => 'attended_event_id'
  has_many :attendees, :through => :event_attendee, :source => :attendee

  def self.past
    self.where("e_date < :today", {today: Date.today.to_s})
  end

  def self.upcoming
    self.where("e_date >= :today", {today: Date.today.to_s})
  end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, :class_name => 'User'
  belongs_to :attended_event, :class_name => 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, :foreign_key => 'creator_id'
  has_many :events, :through => :created_events, :source => :event

  has_many :event_attendee, :foreign_key => 'attendee_id'
  has_many :attended_events, :through => :event_attendee, :source => :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_current_user
    @current_user = User.find_by_id(session[:current_user_id])
  end

  def log_in(user)
    session[:current_user_id] = user.id
  end

  def signed_in(user)
    set_current_user
    user.id == @current_user.id
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :set_current_user
before_action :validate_sign_in, only: [:new, :create,:join]
  def index
    @events = Event.all

  end

  def new
    @event = @current_user.events
  end

  def create
    @event = @current_user.events.create(event_params)
    if @event.save
      flash[:notice] = "Successfully created event"
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
    #.all makes it an array vs an association object?
    @event_attendees = @event.attendees.all

  end

  def join
    @event = Event.find_by_id(params[:id])
    @current_user.attended_events << @event
    flash[:notice] = "Successfully joined event!"
    redirect_to user_path(@current_user)
  end

  private

  def event_params
    params.require(:events).permit(:location, :e_date)
  end

  def validate_sign_in
    if @current_user.nil?
      flash[:notice] = "Please sign in before creating an event!"
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])

    if !@user.nil?
      log_in(@user)
      flash[:success] = "Login successful"
      redirect_to user_path(session[:current_user_id])
    else
      render :new
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to new_user_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :correct_user?, only:[:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @user_events = @user.events.all
    @past_events = @user.attended_events.where("e_date < :today",{today: Date.today.to_s})
    @future_events = @user.attended_events.where("e_date > :today",{today: Date.today.to_s})

  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def correct_user?
    @user = User.find_by_id(params[:id])
    if signed_in(@user) == false
      flash[:error] = "You do not have permission to view."
      redirect_to events_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h2> These are upcoming events! <br/>
  <ul>
  <% Event.upcoming.each do |e| %>
    <li><%= link_to e.location, event_path(e.id) %></li>
  <% end %>
  </ul>
<h2> These are past events! <br/>
  <ul>
  <% Event.past.each do |e| %>
    <li><%= link_to e.location, event_path(e.id) %></li>
  <% end %>
  </ul>

app/views/events/new.html.erb
<%= form_for(:events, url: events_path) do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.date_field :e_date %>

  <%= f.submit 'Create new place!' %>
<% end %>

app/views/events/show.html.erb
<h2> This is the event detail:
  <br/>
  <h4> Location: <%= @event.location%>
  <br/>
  Date: <%= @event.e_date%>
  </h4>
</h2>
<h2> These are the people attending:
  <ul>
    <% @event_attendees.each do |a| %>
      <li> <%= a.name %> </li>
    <% end %>
</h2>
<h2>Would you like to join the event? </h2>
<%= button_to 'Yes',{ action: "join", id: @event.id } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class='container'>
  <h1> Its Private! </h1>
  <%= link_to 'Home', events_path %>

  <% if !@current_user.nil? %>
    <h2>Welcome, <%= @current_user.name %> &#9786; </h2>
    <%= link_to 'User', user_path(@current_user.id) %>
    <%= link_to 'Sign out', session_path(@current_user), method: :delete %>
  <% end %>

  <% flash.each do |error,message| %>
    <%= message %>
  <%end%>

</div>

app/views/users/new.html.erb
<h2> Welcome! Please sign up! </h2>

<%= form_for @user, url: {action:'create'} do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Create' %>
<% end %>

<%= link_to 'Log in', new_session_path %>

app/views/users/show.html.erb
<h2> This is your profile,
  <%= @user.name %>!
</h2>
<h3> These are your created events </h3>
<ul>
  <% @user_events.each do |e| %>
    <li> <%= e.location %> </li>
  <% end %>
</ul>

<% if !@past_events.nil? %>
  <h3> These are your past events </h3>
  <ul>
    <% @past_events.each do |e| %>
      <li> <%= e.location %>  Date: <%= e.e_date %></li>
    <% end %>
  </ul>
<% end %>

<% if !@future_events.nil? %>
  <h3> These are your upcoming events </h3>
  <ul>
    <% @future_events.each do |e| %>
      <li> <%= e.location %>  Date: <%= e.e_date %> </li>
    <% end %>
  </ul>
<% end %>